 wget https://demo.bootstrapdash.com/skydash/themes/assets/vendors/feather/feather.css
  wget https://demo.bootstrapdash.com/skydash/themes/assets/vendors/ti-icons/css/themify-icons.css
  wget https://demo.bootstrapdash.com/skydash/themes/assets/vendors/css/vendor.bundle.base.css
  wget https://demo.bootstrapdash.com/skydash/themes/assets/vendors/font-awesome/css/font-awesome.min.css
 wget  https://demo.bootstrapdash.com/skydash/themes/assets/vendors/datatables.net-bs5/dataTables.bootstrap5.css
 wget  https://demo.bootstrapdash.com/skydash/themes/assets/vendors/ti-icons/css/themify-icons.css
 wget  https://demo.bootstrapdash.com/skydash/themes/assets/js/select.dataTables.min.css
 wget  https://demo.bootstrapdash.com/skydash/themes/assets/css/vertical-layout-light/style.css
 wget  https://demo.bootstrapdash.com/skydash/themes/assets/images/favicon.png
 wget  https://demo.bootstrapdash.com/skydash/themes/assets/vendors/js/vendor.bundle.base.js
 wget  https://demo.bootstrapdash.com/skydash/themes/assets/vendors/chart.js/chart.umd.js
 wget  https://demo.bootstrapdash.com/skydash/themes/assets/vendors/datatables.net/jquery.dataTables.js
 wget  https://demo.bootstrapdash.com/skydash/themes/assets/vendors/datatables.net-bs5/dataTables.bootstrap5.js
 wget  https://demo.bootstrapdash.com/skydash/themes/assets/js/dataTables.select.min.js
  wget https://demo.bootstrapdash.com/skydash/themes/assets/js/off-canvas.js
  wget https://demo.bootstrapdash.com/skydash/themes/assets/js/hoverable-collapse.js
  wget https://demo.bootstrapdash.com/skydash/themes/assets/js/template.js
  wget https://demo.bootstrapdash.com/skydash/themes/assets/js/settings.js
 wget  https://demo.bootstrapdash.com/skydash/themes/assets/js/todolist.js
 wget  https://demo.bootstrapdash.com/skydash/themes/assets/js/jquery.cookie.js
  wget https://demo.bootstrapdash.com/skydash/themes/assets/js/dashboard.js